services:
  migrator:
    build:
      context: .
      target: migrator
    command: npx drizzle-kit migrate
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_DB}
    restart: "no"

  app:
    build:
      context: .
      target: app
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_DB}
