services:
  migrator:
    build:
      context: .
      target: migrator
    command: npx drizzle-kit migrate
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_D}
    restart: "no"

  app:
    build:
      context: .
      target: app
    ports:
      - "3000:3000"
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_DB}
