// @generated drizzle-zero signature:sha256:b051ef3ba0574c6ae5a9e413816c0fc6211992e0385ae140fee1ffb385465680
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const dishGroupsTable = {
    "name": "dishGroups",
    "columns": {
        "id": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        }
    },
    "primaryKey": ["id"],
    "serverName": "dish_groups"
} as const;
const dishesTable = {
    "name": "dishes",
    "columns": {
        "id": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "priceCents": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "price_cents"
        },
        "description": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "groupId": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "group_id"
        }
    },
    "primaryKey": ["id"]
} as const;
const orderItemsTable = {
    "name": "orderItems",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "orderer": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "priceCents": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "price_cents"
        },
        "dishId": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "dish_id"
        },
        "orderId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "order_id"
        }
    },
    "primaryKey": ["id"],
    "serverName": "order_items"
} as const;
const ordersTable = {
    "name": "orders",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const dishesRelationships = {
    "orderItems": [{ "sourceField": ["id"], "destField": ["dishId"], "destSchema": "orderItems", "cardinality": "many" }],
    "group": [{ "sourceField": ["groupId"], "destField": ["id"], "destSchema": "dishGroups", "cardinality": "one" }]
} as const;
const orderItemsRelationships = {
    "dish": [{ "sourceField": ["dishId"], "destField": ["id"], "destSchema": "dishes", "cardinality": "one" }],
    "order": [{ "sourceField": ["orderId"], "destField": ["id"], "destSchema": "orders", "cardinality": "one" }]
} as const;
const ordersRelationships = {
    "items": [{ "sourceField": ["id"], "destField": ["orderId"], "destSchema": "orderItems", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "dishGroups": dishGroupsTable,
        "dishes": dishesTable,
        "orderItems": orderItemsTable,
        "orders": ordersTable
    },
    "relationships": {
        "dishes": dishesRelationships,
        "orderItems": orderItemsRelationships,
        "orders": ordersRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "dishGroups" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DishGroup = Row<(typeof schema)["tables"]["dishGroups"]>;
/**
 * Represents a row from the "dishes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Dish = Row<(typeof schema)["tables"]["dishes"]>;
/**
 * Represents a row from the "orderItems" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type OrderItem = Row<(typeof schema)["tables"]["orderItems"]>;
/**
 * Represents a row from the "orders" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Order = Row<(typeof schema)["tables"]["orders"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
