/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainOrderIdRouteImport } from './routes/train/$orderId'
import { Route as ApiQueryRouteImport } from './routes/api.query'
import { Route as ApiMutateRouteImport } from './routes/api.mutate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainOrderIdRoute = TrainOrderIdRouteImport.update({
  id: '/train/$orderId',
  path: '/train/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMutateRoute = ApiMutateRouteImport.update({
  id: '/api/mutate',
  path: '/api/mutate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/train/$orderId': typeof TrainOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/train/$orderId': typeof TrainOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/train/$orderId': typeof TrainOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/mutate' | '/api/query' | '/train/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/mutate' | '/api/query' | '/train/$orderId'
  id: '__root__' | '/' | '/api/mutate' | '/api/query' | '/train/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMutateRoute: typeof ApiMutateRoute
  ApiQueryRoute: typeof ApiQueryRoute
  TrainOrderIdRoute: typeof TrainOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$orderId': {
      id: '/train/$orderId'
      path: '/train/$orderId'
      fullPath: '/train/$orderId'
      preLoaderRoute: typeof TrainOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mutate': {
      id: '/api/mutate'
      path: '/api/mutate'
      fullPath: '/api/mutate'
      preLoaderRoute: typeof ApiMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMutateRoute: ApiMutateRoute,
  ApiQueryRoute: ApiQueryRoute,
  TrainOrderIdRoute: TrainOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
