/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemotionExportRouteImport } from './routes/remotion-export'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainOrderIdRouteImport } from './routes/train/$orderId'
import { Route as ApiRemotionRenderDownloadRouteImport } from './routes/api.remotion-render-download'
import { Route as ApiQueryRouteImport } from './routes/api.query'
import { Route as ApiMutateRouteImport } from './routes/api.mutate'
import { Route as ApiOrdersOrderIdSummaryVideoRouteImport } from './routes/api.orders.$orderId.summary-video'

const RemotionExportRoute = RemotionExportRouteImport.update({
  id: '/remotion-export',
  path: '/remotion-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainOrderIdRoute = TrainOrderIdRouteImport.update({
  id: '/train/$orderId',
  path: '/train/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemotionRenderDownloadRoute =
  ApiRemotionRenderDownloadRouteImport.update({
    id: '/api/remotion-render-download',
    path: '/api/remotion-render-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMutateRoute = ApiMutateRouteImport.update({
  id: '/api/mutate',
  path: '/api/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdSummaryVideoRoute =
  ApiOrdersOrderIdSummaryVideoRouteImport.update({
    id: '/api/orders/$orderId/summary-video',
    path: '/api/orders/$orderId/summary-video',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/remotion-export': typeof RemotionExportRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/remotion-render-download': typeof ApiRemotionRenderDownloadRoute
  '/train/$orderId': typeof TrainOrderIdRoute
  '/api/orders/$orderId/summary-video': typeof ApiOrdersOrderIdSummaryVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/remotion-export': typeof RemotionExportRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/remotion-render-download': typeof ApiRemotionRenderDownloadRoute
  '/train/$orderId': typeof TrainOrderIdRoute
  '/api/orders/$orderId/summary-video': typeof ApiOrdersOrderIdSummaryVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/remotion-export': typeof RemotionExportRoute
  '/api/mutate': typeof ApiMutateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/remotion-render-download': typeof ApiRemotionRenderDownloadRoute
  '/train/$orderId': typeof TrainOrderIdRoute
  '/api/orders/$orderId/summary-video': typeof ApiOrdersOrderIdSummaryVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/archive'
    | '/remotion-export'
    | '/api/mutate'
    | '/api/query'
    | '/api/remotion-render-download'
    | '/train/$orderId'
    | '/api/orders/$orderId/summary-video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/archive'
    | '/remotion-export'
    | '/api/mutate'
    | '/api/query'
    | '/api/remotion-render-download'
    | '/train/$orderId'
    | '/api/orders/$orderId/summary-video'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/archive'
    | '/remotion-export'
    | '/api/mutate'
    | '/api/query'
    | '/api/remotion-render-download'
    | '/train/$orderId'
    | '/api/orders/$orderId/summary-video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchiveRoute: typeof ArchiveRoute
  RemotionExportRoute: typeof RemotionExportRoute
  ApiMutateRoute: typeof ApiMutateRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiRemotionRenderDownloadRoute: typeof ApiRemotionRenderDownloadRoute
  TrainOrderIdRoute: typeof TrainOrderIdRoute
  ApiOrdersOrderIdSummaryVideoRoute: typeof ApiOrdersOrderIdSummaryVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remotion-export': {
      id: '/remotion-export'
      path: '/remotion-export'
      fullPath: '/remotion-export'
      preLoaderRoute: typeof RemotionExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train/$orderId': {
      id: '/train/$orderId'
      path: '/train/$orderId'
      fullPath: '/train/$orderId'
      preLoaderRoute: typeof TrainOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remotion-render-download': {
      id: '/api/remotion-render-download'
      path: '/api/remotion-render-download'
      fullPath: '/api/remotion-render-download'
      preLoaderRoute: typeof ApiRemotionRenderDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mutate': {
      id: '/api/mutate'
      path: '/api/mutate'
      fullPath: '/api/mutate'
      preLoaderRoute: typeof ApiMutateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/summary-video': {
      id: '/api/orders/$orderId/summary-video'
      path: '/api/orders/$orderId/summary-video'
      fullPath: '/api/orders/$orderId/summary-video'
      preLoaderRoute: typeof ApiOrdersOrderIdSummaryVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchiveRoute: ArchiveRoute,
  RemotionExportRoute: RemotionExportRoute,
  ApiMutateRoute: ApiMutateRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiRemotionRenderDownloadRoute: ApiRemotionRenderDownloadRoute,
  TrainOrderIdRoute: TrainOrderIdRoute,
  ApiOrdersOrderIdSummaryVideoRoute: ApiOrdersOrderIdSummaryVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
